<script setup lang="ts">
import { computed } from 'vue';

// Import all icon components from barrel export
import {
  // Individual Icon components
  AdditionalInformation,
  AgentManagementIcon,
  AnalyticsIcon,
  APIIcon,
  AppCenterIcon,
  AttentionIcon,
  BackIcon,
  BackPaginationIcon,
  BroadcastIcon,
  BulkResolvedIcon,
  ChatIcon,
  ChatTemplateIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardIcon,
  ClockFastForwardIcon,
  CloseIcon,
  CoinStackIcon,
  CopyIcon,
  CreditCardIcon,
  CurrenciesIcon,
  CustomAgentAllocationIcon,
  CustomerIcon,
  CustomerPropertiesIcon,
  DateIcon,
  DeleteIcon,
  DoubleChevronLeftIcon,
  DoubleChevronRightIcon,
  EditFileIcon,
  EditIcon,
  ErrorIcon,
  EyeIcon,
  FileSearchIcon,
  FilterIcon,
  FilterOnIcon,
  GeneralIcon,
  HelpIcon,
  HomeIcon,
  HoursIcon,
  IdentificationIcon,
  InboxIcon,
  InformationIcon,
  IntegrationIcon,
  LineChartIcon,
  LoginIcon,
  LogoutIcon,
  MegaphoneIcon,
  MergeIcon,
  MinusIcon,
  MobileIcon,
  MoreIcon,
  NewspaperIcon,
  NextIcon,
  NextPaginationIcon,
  NotesIcon,
  NotificationIcon,
  OmnichannelIcon,
  OpenTabIcon,
  PackageIcon,
  PlusIcon,
  PredifinedMessageIcon,
  PresentationIcon,
  PuzzleIcon,
  QCRMIcon,
  QiscusIcon,
  QTicketingIcon,
  RefreshIcon,
  ReplyIcon,
  RobolabsIcon,
  SearchIcon,
  SendIcon,
  SettingIcon,
  ShopIcon,
  SquareIcon,
  SubmitTicketIcon,
  SubscriptionIcon,
  SuccessIcon,
  TagsIcon,
  TemplateMessageIcon,
  TrendingIcon,
  User3Icon,
  UserCircleIcon,
  UserIcon,
  WarningIcon,
  WhatsappBusinessIcon,
  WindowIcon,
  WorkFlowIcon,
  SignIcon,
  // Channel Icons
} from './index';

interface IconProps {
  name: string;
  size?: number;
  class?: string;
}

const props = withDefaults(defineProps<IconProps>(), {
  size: 24,
  class: '',
});

// Icon registry - maps icon names to components
const iconRegistry = {
  inbox: InboxIcon,
  broadcast: BroadcastIcon,
  customer: CustomerIcon,
  analytics: AnalyticsIcon,
  integration: IntegrationIcon,
  'app-center': AppCenterIcon,
  robolabs: RobolabsIcon,
  ticketing: QTicketingIcon,
  qcrm: QCRMIcon,
  workflow: WorkFlowIcon,
  mobile: MobileIcon,
  setting: SettingIcon,
  help: HelpIcon,
  logout: LogoutIcon,
  'filter-on': FilterOnIcon,
  'chat-template': ChatTemplateIcon,
  notes: NotesIcon,
  'credit-card': CreditCardIcon,
  user: UserIcon,
  'predifined-message': PredifinedMessageIcon,
  hours: HoursIcon,
  tags: TagsIcon,
  'bulk-resolved': BulkResolvedIcon,
  send: SendIcon,
  'customer-properties': CustomerPropertiesIcon,
  notification: NotificationIcon,
  search: SearchIcon,
  subscription: SubscriptionIcon,
  merge: MergeIcon,
  eye: EyeIcon,
  'custom-agent-allocation': CustomAgentAllocationIcon,
  'template-message': TemplateMessageIcon,
  'submit-ticket': SubmitTicketIcon,
  'whatsapp-business': WhatsappBusinessIcon,
  general: GeneralIcon,
  'agent-management': AgentManagementIcon,
  api: APIIcon,
  copy: CopyIcon,
  information: InformationIcon,
  more: MoreIcon,
  plus: PlusIcon,
  filter: FilterIcon,
  edit: EditIcon,
  refresh: RefreshIcon,
  puzzle: PuzzleIcon,
  success: SuccessIcon,
  error: ErrorIcon,
  attention: AttentionIcon,
  warning: WarningIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-down': ChevronDownIcon,
  'next-pagination': NextPaginationIcon,
  'back-pagination': BackPaginationIcon,
  close: CloseIcon,
  back: BackIcon,
  next: NextIcon,
  shop: ShopIcon,
  'chat': ChatIcon,
  minus: MinusIcon,
  check: CheckIcon,
  'additional-information': AdditionalInformation,
  date: DateIcon,
  reply: ReplyIcon,
  currencies: CurrenciesIcon,
  'coin-stack': CoinStackIcon,
  'file-search': FileSearchIcon,
  'clock-fast-forward': ClockFastForwardIcon,
  'line-chart': LineChartIcon,
  login: LoginIcon,
  identification: IdentificationIcon,
  window: WindowIcon,
  package: PackageIcon,
  newspaper: NewspaperIcon,
  megaphone: MegaphoneIcon,
  'edit-file': EditFileIcon,
  presentation: PresentationIcon,
  'user-3': User3Icon,
  clipboard: ClipboardIcon,
  delete: DeleteIcon,
  'open-tab': OpenTabIcon,
  trending: TrendingIcon,
  square: SquareIcon,
  'user-circle': UserCircleIcon,
  omnichannel: OmnichannelIcon,
  // Common icons
  home: HomeIcon,
  'double-chevron-left': DoubleChevronLeftIcon,
  'double-chevron-right': DoubleChevronRightIcon,
  qiscus: QiscusIcon,
  sign: SignIcon,
};

const iconComponent = computed(() => {
  const iconName = props.name.toLowerCase();
  return iconRegistry[iconName as keyof typeof iconRegistry];
});

const iconClasses = computed(() => {
  return `inline-block ${props.class}`;
});
</script>

<template>
  <component v-if="iconComponent" :is="iconComponent" :size="size" :class="iconClasses" />
  <span v-else class="text-red-500"> Icon "{{ name }}" not found </span>
</template>
